export const cities = [
  { id: "1", cityName: "Casablanca" },
  { id: "2", cityName: "Rabat" },
  { id: "3", cityName: "Fes" },
  { id: "4", cityName: "Marrakech" },
  { id: "5", cityName: "Tangier" },
  { id: "6", cityName: "Agadir" },
  { id: "7", cityName: "Meknes" },
  { id: "8", cityName: "Oujda" },
  { id: "9", cityName: "Kenitra" },
  { id: "10", cityName: "Tetouan" },
  { id: "11", cityName: "Safi" },
  { id: "12", cityName: "El Jadida" },
  { id: "13", cityName: "Nador" },
  { id: "14", cityName: "Mohammedia" },
  { id: "15", cityName: "Beni Mellal" },
  { id: "16", cityName: "Khouribga" },
  { id: "17", cityName: "Al Hoceima" },
  { id: "18", cityName: "Taza" },
  { id: "19", cityName: "Essaouira" },
  { id: "20", cityName: "Settat" },
  { id: "21", cityName: "Larache" },
  { id: "22", cityName: "Khemisset" },
  { id: "23", cityName: "Guelmim" },
  { id: "24", cityName: "Ouarzazate" },
  { id: "25", cityName: "Dakhla" },
  { id: "26", cityName: "Laayoune" },
  { id: "27", cityName: "Taroudant" },
  { id: "28", cityName: "Ifrane" },
  { id: "29", cityName: "Midelt" },
  { id: "30", cityName: "Azrou" },
];

export const categories = [
  { id: "1", categoryName: "Music" },
  { id: "2", categoryName: "Sports" },
  { id: "3", categoryName: "Arts & Theater" },
  { id: "4", categoryName: "Business" },
  { id: "5", categoryName: "Technology" },
  { id: "6", categoryName: "Education" },
  { id: "7", categoryName: "Health & Wellness" },
  { id: "8", categoryName: "Food & Drink" },
  { id: "9", categoryName: "Community" },
  { id: "10", categoryName: "Fashion" },
  { id: "11", categoryName: "Film & Media" },
  { id: "12", categoryName: "Travel & Outdoor" },
  { id: "13", categoryName: "Charity & Causes" },
  { id: "14", categoryName: "Government & Politics" },
  { id: "15", categoryName: "Religion & Spirituality" },
  { id: "16", categoryName: "Family & Education" },
  { id: "17", categoryName: "Festivals & Fairs" },
  { id: "18", categoryName: "Science & Nature" },
  { id: "19", categoryName: "Holiday" },
  { id: "20", categoryName: "Gaming" },
];
